spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-server}:5432/ompay
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

app:
  base-url: https://api.ompay.sn