spring.application.name=ompay

# --- Configuration de la base de données PostgreSQL ---
spring.datasource.url=jdbc:postgresql://dpg-d47k0g6mcj7s73demmag-a.frankfurt-postgres.render.com:5432/ompaymobile_ousmane_marra
spring.datasource.username=ompaymobile_ousmane_marra_user
spring.datasource.password=JG6WmsLNCs2HhysWDGRRajVpXR6N3woq

# --- Configuration de JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Port de l'application ---
server.port=8080
