spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-server}:5432/ompay
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

app:
  base-url: https://api.ompay.sn

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}